def print_help():
    print()
    print("Overview")
    print("========")
    print("This is a simple CPU-s enumlator.")
    print()
    print("To run a assembly program, you have two choices:")
    print("\t 1. \"rf (the name of the text file where your program is stored)\"")
    print("\t    - This option runs the program without any interruption.")
    print("\t 2. \"rs (the name of the text file where your program is stored)\"")
    print("\t    - This option waits for user input after each operation has executed")
    print()
    print("The data memory is stored in \"dm.txt\".")
    print("Each line in this document corresponds to a memory cell.")
    print()
    print("Components")
    print("==========")
    print("Accumulator (acc)")
    print("Data register 1 (dr1)")
    print("Data register 2 (dr2)")
    print("Instruction pointer (ip)")
    print()
    print("Instruction set")
    print("===============")
    print("jmp <addr> - Jumps to the instruction line specified by <addr>")
    print("ld1 <addr> - Places <addr> into data pointer 1")
    print("ld2 <addr> - Places <addr> into data pointer 2")
    print("sto - Writes the value in the accumulator into data memory using address specified by data pointer 1")
    print("add - acc <- DR1 + DR2")
    print("sub - acc <- DR1 - DR2")
    print("mlt - acc <- DR1 * DR2")
    print("hlt - Halts the program")
    print()
    print()
